#!/bin/sh
chown=$CHOWN
chmod=$CHMOD
chgrp=$CHGRP
MANGROUPNAME=$NETGROUPNAME
MANUSERNAME=$NETUSERNAME
case "$ISPOOLDIR" in
'')	ISPOOLDIR=/usr/spool/MHSnet	;;
esac

rm -rf $ISPOOLDIR/_man
mkdir $ISPOOLDIR/_man || exit 1
for i in 1 5 7 8
do
	mkdir $ISPOOLDIR/_man/man$i || exit 1
done
cp *.1T $ISPOOLDIR/_man/man1 || exit 1
cp *.5T $ISPOOLDIR/_man/man5 || exit 1
cp *.7T $ISPOOLDIR/_man/man7 || exit 1
cp *.8T $ISPOOLDIR/_man/man8 || exit 1

cd $ISPOOLDIR/_man

$chmod u=rwx,go=rx . *
$chmod u=rw,go=r */*
$chown $MANUSERNAME . * */*
$chgrp $MANGROUPNAME . * */*

for i in */*T
do
	case $0 in
	*s)	x=`expr $i : '\(.*\)\.[0-9]T'`
		;;
	*)	x=`expr $i : '\(.*\)T'`
		;;
	esac
	mv "$i" "$x"
done

case $0 in
*TZs|*TZ)
	compress -f */*
	;;
*Tgzs|*Tgz)
	gzip -f */*
	;;
*Tzs|*Tz)
	pack -f */*
	;;
esac

ls -ld */*

exit 0
