.nr S0 0 \" 1 for directory forwarding
.ds S1 NETGET
.ds S2 Netget
.ds S3 netget
.ds S4 MHSnet
.ds S5 network
.TH \*(S1 1 "\*(S4 1.11" \^
.nh
.SH NAME
netget \- get files spooled from network
.SH SYNOPSIS
.BI \*(S3
.RI [\- flags \|]
.RI [ filename
\&...]
.SH DESCRIPTION
.I \*(S2
will retrieve files spooled from the network in the spool area
(as reported by
.IR mail (1)).
.I \*(S2
finds all the files spooled for the invoker,
prints out the number of files found,
sorts them into
.I "modify time"
order,
and then prompts for each file
for the invoker to decide on the action to be taken,
(reply
.if t \f(CWappend\fP,
.if n `append',
.if t \f(CWbasename\fP,
.if n `basename',
.if t \f(CWcd\fP,
.if n `cd',
.if t \f(CWdelete\fP,
.if n `delete',
.if t \f(CWkeep\fP,
.if n `keep',
.if t \f(CWmkdir\fP,
.if n `mkdir',
.if t \f(CWno\fP
.if n `no'
[default],
.if t \f(CWquit\fP,
.if n `quit',
.if t \f(CWrename\fP
.if n `rename'
or
.if t \f(CWyes\fP
.if n `yes'
as appropriate \(em
the first letter is sufficient).
The \fIyes\fP action is to copy the file into the path name indicated,
and delete the spooled copy.
If the reply is
.if t \f(CWcd\fP,
.if n `cd',
.if t \f(CWmkdir\fP
.if n `mkdir'
or
.if t \f(CWrename\fP
.if n `rename'
and no path name is supplied after the command,
then
.I \*(S3
will prompt you for a new pathname.
The \fIkeep\fP command effect is the same as for \fIyes\fP,
but the file will not be deleted after copying
(can be default for all files with the \fB\-k\fP flag below).
.PP
Any filename arguments will restrict the selection to those named.
.PP
.I \*(S2's
action may be modified by the following flags:
.if n .ds tw 4
.if t .ds tw \w'\fB\-S\fP\fI\ sender\fPX'u
.TP "\*(tw"
.BI \-delete
Delete all (named) files.
.TP
.BI \-1
Only get the first file with the same name as the argument.
.TP
.BI \-a
Search for all files, rather than just those belonging to the invoker.
The name of the recipient will also be printed.
The default sort order is on name of recipient.
This flag is restricted to the network
.I super-user .
.TP
.BI \-b
Truncate all file pathnames to their last component.
(cf: "basename" command above.)
.TP
.BI \-c
Do a check of the CRC on the data if it exists.
(Generated by the \fB\-c\fR flag to
.IR netfile (1)
and checked automatically by the file handler on reception.)
.TP
.BI \-d
Create directories as needed to match pathnames of retrieved files.
.TP
.BI \-e
Files will be sorted by delivery time.
The delivery time of the message
will be printed instead of the modify time of the file,
unless \fIverbose\fP mode is selected,
in which case both will be printed.
.TP
.BI \-f
Set, or unset, file forwarding for the invoker.
A second argument should be supplied which is an address for files to be forwarded to.
.if \n(S0 \{\
Alternatively it may be the name of a directory where incoming files should be spooled.\}
A missing argument implies that forwarding should be turned off.
See also
.IR netforward (1).
.TP
.BI \-k
Keep all files \(em don't delete any files retrieved from messages.
This causes the \fIdelete\fP command to be ignored.
Individual files may also be retained after retrieval (cf: the \fIkeep\fP command above).
.TP
.BI \-l
The (named) files will be listed only.
.TP
.BI \-m
Files will be sorted by modify time [default].
.TP
.BI \-n
Files will be sorted by name.
.TP
.BI \-o
The named files will be copied to
.IR stdout .
They will not then be deleted unless the flag
.I \-delete
is used.
.TP
.BI \-r
The order of the sort will be reversed.
.TP
.BI \-s
Do it silently.
.TP
.BI \-t
Files will be sorted by transmit time.
The transmit time of the message
will be printed instead of the modify time of the file,
unless \fIverbose\fP mode is selected,
in which case both will be printed.
.TP
.BI \-u
Don't set the modify date for the retrieved file
back to the original for the transmitted file.
.TP
.BI \-v
Give a verbose description of each file,
including full destination address,
and route taken.
The delivery time for the message will also
be printed before the modify time for the file.
.TP
.BI \-x
Just report the number of (named) files spooled
(unless the flag \fB\-s\fP is elected),
and return the number as the exit status (max. 127).
.TP
.BI \-y
Assume answer `yes' to all questions.
.TP
.BI \-F " source"
Only consider messages sent from the site
.IR source .
.TP
.BI \-O " days"
Only consider messages older than
.IR days .
.TP
.BI \-S " sender"
Only consider messages sent by the person
.IR sender .
.TP
.BI \-T \fR[\fPlevel\fR]\fP
Turns on tracing at
.I level
(default: 1).
If tracing is not compiled in,
this flag will have no effect.
.TP
.BI \-U " name"
The name of the user whose files are to be retrieved is changed to
.IR name .
This flag is restricted to the
.IR super-user .
.TP
.BI \-?
Explain argument options and exit.
.PP
Either one of \fB\-F\fP or \fB\-S\fP (but not both) may be specified as in
.BI \-F sender @ source .
.PP
.I \*(S2
will create the files with the mode of the original as modified
by your file creation mask
(see
.IR umask (1)).
.SH EXAMPLES
Show all files spooled sorted by name:
.PP
.RS 2
.ft CW
\*(S3 -ln
.ft
.RE
.PP
Retrieve, and rename, a particular file sent by
.I judy
from
.IR basser.cs.su.oz.au :
.PP
.RS 2
.ft CW
\*(S3 -1os -delete -Fjudy@basser.cs.su.oz.au f.c >n.c
.ft
.RE
.PP
Forward your files to two other users:
.PP
.RS 2
.ft CW
\*(S3 -f john@cs.mu.oz.au fred@sw.oz.au
.ft
.RE
.PP
Any addresses will be expanded to canonical form.
.SH FILES
.PD 0
.TP "\w'_forward/\fPusername\fPX'u"
_files/*
Spooled files.
.TP
_forward/\fIusername\fP
Forwarding details for user.
.TP
_state/routefile
Routing tables for resolving addresses.
.PD
.SH "SEE ALSO"
.IR netfetch (1),
.IR netfile (1),
.IR netforward (1),
.IR umask (1).
