.ds S1 NETMAIL
.ds S2 \fINetmail\fP
.ds S3 \fInetmail\fP
.ds S4 MHSnet
.ds S5 network
.ds S6 netmail
.TH \*(S1 1 "\*(S4 1.26" \^
.nh
.SH NAME
netmail \- send mail via network
.SH SYNOPSIS
.BI \*(S3
.RI [\- flags ]
.RI [ NAME = value "] ..."
.IR users [\c
.BI @ destinations\c
] ...
.SH DESCRIPTION
\*(S2
is a simple program to send a mail message to remote users via the network.
A mail message consists of two parts: the
.I header,
which must contain certain lines,
followed by the
.IR body ", or " text ,
which may be empty.
\*(S2
starts in
.I composition
mode,
allowing the invoker to change any line in the header,
and add to or edit the text.
Composition terminates when
\*(S3
reads a line consisting of a single period.
It then sends the mail using
.IR netfile (1).
.PP
\*(S2
will concatenate all
.I To
and
.I "carbon copy"
recipients into a
.I multicast
address so that a minimal number of network
message copies will be generated for multiple destinations.
A separate message is generated for
.I "blind carbon copy"
recipients,
whose addresses are not seen by the others.
.PP
The flags are as follows:
.PP
.if n .ds tw 4
.if t .ds tw \w'\s-1NAME\s0\fB=\fP\fIXstringX\fPX'u
.TP "\*(tw"
.BI \-a
Turns on message acknowledgement,
and reports a unique identifier on
.IR stdout .
You will receive an automatic acknowledgement of delivery
tagged with the identifier from each recipient.
This flag may also be set with the
.B ".A"
command, or toggled with the
.B ".a"
command (see \s-1COMMANDS\s0 below).
.TP
.BI \-b
Prompt for a 
.I "blind carbon copy"
list
(unless set via the
.SM BCC
environment variable as below).
.TP
.BI \-c
Prompt for a 
.I "carbon copy"
list
(unless set via the
.SM CC
environment variable as below).
.TP
.BI \-d
Incorporate the `dead.letter' file.
The mail header lines are also set from the incorporated file.
The same effect may also be achieved with the
.B ".D"
command (see \s-1COMMANDS\s0 below).
.TP
.BI \-e
Add a `Received:' line to the mail header.
.TP
.BI \-f
Read and send a letter with mail-header and body both from
.IR stdin .
The header is checked and addresses are canonicalised.
(Sets \fB\-st\fP.)
.TP
.BI \-i
Add a `Message-ID:' line to the mail header.
.TP
.BI \-m
Ignore commands from
.I stdin
\(em add all input to body of mail. 
.TP
.BI \-o
Do not allow the first period to be interpreted as an address separator in address arguments.
(This is normally considered an alternative address separator if there is no `@' present).
.TP
.BI \-p
Print header on startup.
.TP
.BI \-q
Report a unique message identifier generated for the mail item(s) on
.IR stdout .
A unique message identifier is also generated by the \fB\-a\fP flag above,
however, this flag suppresses the explanatory leader.
.TP
.BI \-r
Requests that mail should not be returned on error.
.TP
.BI \-s
Don't prompt for a `Subject:' line
(the default action is to prompt).
.TP
.BI \-t
Don't echo `To:' or `EOT' to
.IR stdout .
.TP
.BI \-F \ file
Use
.I file
as default if no name supplied with the `.m' or `.r' incorporate commands (below).
.TP
.BI \-T \fR[\fPlevel\fR]\fP
Turns on tracing at
.I level
(default: 1).
If tracing is not compiled in,
this flag will have no effect.
.TP
\s-1NAME\s0\fB=\fP\fI"string"\fP
Set specific environment variables as described below.
These values override those in the environment.
.TP
.BI \-?
Explain argument options and exit.
.PP
Other arguments are assumed to be the addresses of mail recipients
to be included in the
.I To
line.
The default
.I destination
is the local site, which will be interpolated.
Other destination addresses supplied will be expanded using the network routing tables.
See
.IR netfile (1)
for the full syntax for 
.IR destinations ,
but note that 
.I user
addresses are different,
in that a comma (`\fB,\fP') between user names
has the same effect as a space.
.SH "ENVIRONMENT VARIABLES"
\*(S2
understands several
.I environment
variables that control its actions:
.PP
.if n .ds tw 4
.if t .ds tw \w'\s-1ORGANIZATION\s0X\fP'u
.TP "\*(tw"
.SM ADDRESS
Sets the
.I site
address for the invoker,
which will be used as the invoker's source address in the mail header `From: ' line.
The default is the value of the local host address minus the leading node-name
(or the value of the configuration parameter
.SM ADDRESS
if set).
A suitable value can be obtained by using
.IR netaddr (8)
eg:
.br
\f(CW\ \ ADDRESS=`netaddr -s` export ADDRESS\fP
.TP
.SM BCC
.I "Blind carbon copy"
recipients.
These recipients will receive a copy of the full text of the mail message,
whereas users in the
.I To
and
.I Cc
lists will not see these addresses.
The use of
.SM BCC
necessarily entails the transmission of two separate messages.
.TP
.SM CC
.I "Carbon copy"
recipients.
.TP
.SM EDITOR
The pathname of a program to be invoked to edit the message.
.TP
.SM LINES
The number of lines in the current window (default 22).
.TP
.SM LOGNAME
The
.I "login name"
of the invoker.
The default will be extracted from the
.I passwd
file.
This variable overrides the default,
so make sure that the name is a deliverable address for received mail messages.
(Alternatives:
.SM LNAME
or
.SM USER\c
\&.)
.TP
.SM NAME
The invoker's full name.
This will be added to the
.I From
line in parentheses.
The default is extracted from the
`pw_gecos'
field in the
.I passwd
file if it is non-empty \(em which may not be what you want.
This variable overrides the default.
.TP
.SM ORGANIZATION
Sets value for optional `Organisation: ' field in message header.
.TP
.SM OUTBOX
If this variable is set to the name of a file,
\*(S3
will append a copy of the mail to it when the mail is sent.
If instead
.SM OUTBOX
is a directory,
then the mail will be appended to a file in that directory
with the name of the first recipient.
Alternatively,
it can be a space separated list of files and/or directories,
in which case
each will receive a copy of the mail message after composition.
.TP
.SM PAGER
The pathname of a program to paginate output from the `.p' command.
.TP
.SM SIGNATURE
The name of a file to be appended to the body of the mail.
By default this file is assumed to be called `.signature'
in the invoker's home directory, but if this variable is set,
then it will force inclusion of the signature file at the end of the mail.
The same effect may be achieved with the \fB.g\fP command
(see \s-1COMMANDS\s0 below).
.TP
.SM SUBJECT
Description for the
.I Subject
line in the mail header.
You will be prompted to supply a subject
if this variable is missing\c
\(eman empty response removes the line.
.TP
.SM XFACE
Sets value for optional `X-Face: ' field in message header.
.SH COMMANDS
.I Composition
mode allows several commands.
Some change specific fields in the header,
others affect the whole message, or just the message
.IR body .
If the command takes an optional parameter,
and the parameter is missing,
it will prompt you for it.
A space between command and parameter is optional.
In general, the upper-case variant of each command has a
.I setting
effect, whereas the lower-case command has a
.IR modifying ,
or
.I appending
effect.
All commands start with a period at the beginning of a line,
and end with a
.IR newline :
.PP
.if n .ds tw 6
.if t .ds tw \w'\fB.<\fP\fI\ prog\ [arg\ ...]\fPX'u
.TP "\*(tw"
.BI .! \ prog\ [arg\ ...]
Execute
.I prog
with optional arguments.
.TP
.BI .< \ prog\ [arg\ ...]
Append the output of
.I prog
to the body of the message.
.TP
.BI .| \ prog\ [arg\ ...]
Pipe the body of the message though
.IR prog .
.TP
.BI ".a" " " ".A"
Toggle (a), or set (A), the value of the
.I acknowledgement
flag.
.TP
.BI ".b" " " ".B" \ [list]
Add to (b), or replace (B), the list of recipients for
.IR "blind carbon copies" .
.TP
.BI ".c" " " ".C" \ [list]
Add to (c), or replace (C), the list of recipients for
.IR "carbon copies" .
.TP
.BI ".d" " " ".D"
Append (d), or replace whole message by (D),
the `dead.letter' file.
.TP
.BI ".e" " " ".E" \ [editor]
Edit whole message (e), or message body (E).
The name of the editor invoked is taken from the optional
.I editor
argument, otherwise from the
.SM EDITOR
environment variable if it exists,
otherwise from the
.SM EDITOR
parameter if it is set in the \*(S3 parameter file,
otherwise
.IR ed (1)
is used.
.TP
.BI ".f" " " ".F" \ [list]
Append to (f), or replace (F), the outbox recipient list.
This list defaults to the name of the first recipient in the
.I To:
list.
It is used if any name in the
.SM OUTBOX
list above is the pathname of a directory,
in which case the message will be appended
to each file that can be created by appending
a name from the recipient list
to the name of a directory in the
.SM OUTBOX
list.
.TP
.BI ".g" " " ".G" \ [file]
Append (g), or replace message body by (G),
the contents of
.IR file .
[Default:
.if n `$HOME/.signature',
.if t \f(CW$HOME/.signature\fP,
unless overridden by the \s-1SIGNATURE\s0 variable.]
.TP
.BI ".m" " " ".M" \ [file]
Append (m), or replace message body by (M),
the contents of
.I file
shifted right one tab stop.
If
.I file
is missing,
it defaults to the name supplied with the \fB\-F\fP argument.
.TP
.BI ".o" " " ".O" \ [list]
Append to (o), or replace (O), the list of outboxes.
Names in the
.I list
should be those of files and/or directories which are treated as for
.SM OUTBOX
above.
.TP
.BI ".p" " " ".P"
Print whole message (p), or message body (P).
The output is piped through a paginator if more than
.SM LINES
lines (default 22).
The pathname of the paginator invoked is taken from the
.SM PAGER
environment variable if it exists,
otherwise
.IR more (1)
is used.
.TP
.BI ".r" " " ".R" \ [file]
Append (r), or replace whole message by (R),
the contents of
.IR file .
If
.I file
is missing,
it defaults to the name supplied with the \fB\-F\fP argument.
.TP
.BI ".s" " " ".S" \ [sentence]
Add to (s), or replace (S), the
.I Subject
line with
.IR sentence .
.TP
.BI ".t" " " ".T" \ [list]
Add to (t), or replace (T), the list of recipients on the
.I To
line.
.TP
.BI ".u" " " ".U" \ [file]
Append (u), or replace whole message by (U),
the contents of
.I file
in `uuencode'd form (see
.IR uuencode(1)).
If
.I file
is missing,
it defaults to the name supplied with the \fB\-F\fP argument.
.TP
.BI ".w" " " ".W" \ file
Write the message onto
the end of (w), or over (W),
.IR file .
.TP
.BI ".?" " " ".h"
Print a short summary of these commands.
.TP
.BI "."
Terminate composition and send mail.
.PP
Any other line beginning with a period is incorporated into the body of the message.
.PP
Note that the
.BI .u
command is a short form of:
.RS
.if t .ft CW
 .<uuencode \fIfile\fP
.if t .ft R
.RE
Ie: a way of including binary data
in mail messages to sites not running \*(S4
(otherwise use
.IR netfile (1)).
A smaller mail message can be produced by:
.RS
.if t .ft CW
 .<compress <\fIfile\fP | uuencode \fIfile\fP.Z
.if t .ft R
.RE
or, even smaller:
.RS
.if t .ft CW
 .<gzip <\fIfile\fP | uuencode \fIfile\fP.gz
.if t .ft R
.RE
.SH PARAMETERS
On starting,
\*(S3 reads a file in the `_params' directory with the same name as it was invoked under.
(Ie: if you typed
.if n `netmail'
.if t \f(CWnetmail\fP
to invoke \*(S3,
it will look in the configuration file called
.if n `SPOOLDIR/_params/netmail'.)
.if t \s-1SPOOLDIR\s0\fCW/_params/netmail\fP.)
This file can contain the following optional parameters:
.if n .ds tw 4
.if t .ds tw \w'\s-1ORGANIZATION\s0X'u
.TP "\*(tw"
.SM ACKMAIL
Turn on message acknowledgment for all mail.
.TP
.SM ADDRESS
Overrides default `site' address.
.TP
.SM EDITOR
The pathname of a program to be invoked to edit the message.
.TP
.SM MESSAGEID
Add a
.if n `Message-ID: '
.if t \f(CWMessage-ID:\fP
line to all mail message headers.
.TP
.SM NORET
Request that all errors at destinations be ignored.
.TP
.SM ORGANIZATION
Sets value for optional `Organisation: ' field in message header.
.TP
.SM PAGER
The pathname of a program to paginate output from the `.p' command.
.TP
.SM RECEIVED
Add a
.if n `Received: '
.if t \f(CWReceived:\fP
line to all mail message headers.
.TP
.SM SENDACKARGS
A string representing the arguments to be passed to
.SM SENDER
below that will be used if message acknowledgement is selected.
.TP
.SM SENDARGS
A string representing the arguments to be passed to
.SM SENDER
below that will be used if message acknowledgement is not selected.
.TP
.SM SENDER
The name of the program to be invoked to send the mail message.
It will have the data for the message piped into its standard input,
and will be invoked with one of the two sets of arguments above.
.TP
.SM XFACE
Sets value for
.I organisational
`X-Face: ' field in message header.
.SH FILES
.if n .ds tw 4
.if t .ds tw \w'\f(CW$HOME/dead.letter\fPX'u
.TP "\*(tw"
\f(CW$HOME/dead.letter\fP
The file created to contain a mail message
if composition is aborted before transmission.
The mail message is always
.I appended
to this file.
.TP
\f(CW$HOME/.signature\fP
The default name for the file used by the \fB.g\fP command.
.TP
\f(CW$OUTBOX\fP
A list of file path names created to contain a copy of outgoing mail.
The mail message is always
.I appended
to these files.
.TP
\f(CW$OUTBOX/\fP\fIname\fP
If any path name in
.SM OUTBOX
is a directory, then a file will be
created in that directory for each name in the outbox recipient list
(cf: the \fB.f\fP command).
Default: the name of the first recipient of the mail.
The mail message is always
.I appended
to these files.
.TP
\f(CW_params/\fP\fInetmail\fP
Optional parameters for \*(S3 where
.I netmail
is the same name as \*(S3 was invoked under.
.br
.ne 3
.SH "SEE ALSO"
.IR compress (1),
.IR ed (1),
.IR netfile (1),
.IR more (1),
.IR uuencode(1),
.IR netaddr (8).
.SH BUGS
\*(S2
is not a mail
.I reading
program.
.PP
\*(S2
bypasses local mail processing by programs such as
.IR sendmail ,
and while this means that it incurs less overhead,
it also means that it will only accept addresses that the network knows about.
