.nr S3 1 \" 1 for ACSnet
.ds S1 NETPARAMS
.ds S2 \fINetparams\fP
.ds S3 \fInetparams\fP
.ds S4 MHSnet
.ds S5 network
.if t .ds MP \f(CWMHSnetparams\fP
.if t .ds NP \f(CW/usr/lib/MHSnetparams\fP
.if t .ds sD \s-1\f(NBSPOOLDIR\fP\s0
.if t .ds sN \s-1MHS\s0net
.if n .ds MP MHSnetparams
.if n .ds NP `/usr/lib/MHSnetparams'
.if n .ds sD SPOOLDIR
.if n .ds sN MHSnet
.ds sT \v'-0.2v'\s-1*\s0\v'0.2v'
.TH \*(S1 5 "\*(S4 1.34" \^
.nh
.SH NAME
netparams \- network program parameter setting files
.SH SYNOPSIS
.BI /usr/lib/MHSnetparams
.br
.BI \s-1SPOOLDIR\s0/_params/ handler
.SH DESCRIPTION
These files provide an optional parameter changing facility.
The network is configured with the defaults listed below,
but any of these defaults can be changed
by editing the relevant parameter file to set the new value.
.PP
The basic parameter file that affects all network programs is
\*(NP.
It is installed in a
.I well-known
location principally because
it allows the network operating directory to be altered.
The other parameter files
are named after the programs whose operations they affect,
and are found in the directory
.if t \*(sD\f(CW/_params\fR.
.if n `\*(sD/_params'.
Note that only parameters specific to \*(NP should be placed there,
others should be set in their respective program-specific files
as described below.
.PP
The program
.IR netparams (8)
displays the default or altered parameter settings.
.SH MACROS
Some parameters represent arguments
passed to programs called by the network message handlers.
There are some macros that can be used inside arguments
to interpolate fields from the message being processed by the handler,
they are all identified by the special character \fB&\fP:
.PP
.if t .RS 2
.TP "\w'\fB&D\fP	\fIData\ name.\*(sT\fPXX'u"
.BI &D "	Data name." \*(sT
The name of the data in the message.
.TP
.BI &E "	Error."
The value of the error field in the message header.
.TP
.BI &F "	From." \*(sT
The name of the sender of the message.
.TP
.BI &H "	Home."
The name of the destination host (on which the program is being invoked).
.TP
.BI &L "	Link."
The name of the link on which the message arrived.
.TP
.BI &O "	Origin."
The name of the host from which the message originated.
.TP
.BI &S "	Size."
The size of the data in the message.
.TP
.BI &T "	Start time."
The time that the message was inserted into the network at its origin
(\s-1GMT\s0).
.TP
.BI &U "	User." \*(sT
The name of the user to which the message is being delivered.
.TP
.BI &&
The way to escape an \fB&\fP.
.TP
.BI &%
The way to escape a \fB%\fP (see below).
.if t .RE
.PP
Those marked with an asterisk are only valid for messages containing \s-1FTP\s0.
[Messages containing `File Transfer Protocol' are generated by
.IR netfile (1).]
.PP
There is a set of macros related to the above
that can be used to interpolate a string
depending on the presence of absence of a value
associated with the `\fB&\fP' macro of the same name.
If the string is not interpolated the macro is replaced by the null string,
and if this causes the entire argument to become empty it is
omitted from the list of arguments.
These macros are all enclosed by the special character \fB%\fP, and
take the form:
.PP
.RS
\fB%\fP{\fB+\fP|\fB\-\fP}\fBX\fP\fIstring\fP\fB%\fP
.RE
.PP
The \fIstring\fP is interpolated if the form \fB+X\fP is used
and the `\fB&\fP' macro would yield a non-empty string,
or if the form \fB\-X\fP is used
and the `\fB&\fP' macro would yield an empty string. Eg:
.PP
.RS
.if t \f(CW%+Llink%\fP
.if n %+Llink%
.RE
.PP
will interpolate `link' if the macro \fB&L\fP would yield a non-empty link name.
.PP
There is another set of macros that can be used to interpolate a string
depending on the evaluation of a simple boolean expression.
If the string is not interpolated the macro is replaced by the null string,
and if this causes the entire argument to become empty it is
omitted from the list of arguments.
These macros are all enclosed by the special character \fB%\fP, and
take the form:
.PP
.RS
\fB%\fP[\fB!\fP]\fBX\fP\fIstring\fP\fB%\fP
.RE
.PP
If the condition selected by \fBX\fP evaluates to \fBtrue\fP
and the optional \fB!\fP was not given
then \fIstring\fP is interpolated.
Where the \fB!\fP is given \fIstring\fP is interpolated
when the condition evaluates to \fBfalse\fP.
The \fIstring\fP given may contain \fB&\fP substitutions,
however nested \fB%\fP substitutions are not permitted.
.PP
Selector characters (\fIX\fP) are:
.PP
.if t .RS 2
.TP "\w'\fB\fPXX'u"
.B A
True if the message is an acknowledgement.
.TP
.B B
True if the message has a
.I broadcast
address.
.TP
.B D
True if the message might have been duplicated.
.TP
.B H
True if \fB&O\fP is identical with \fB&H\fP,
ie: if the message originated at the destination node.
.TP
.B L
True if \fB&O\fP is not identical with \fB&L\fP,
ie: if the message did not originate at the neighbour node.
.TP
.B Q
True if the message has requested an acknowledgement.
.TP
.B R
True if the message has been returned.
.TP
.B T
True if the message has been truncated.
.if t .RE
.SH PARAMETERS
Parameters are defined the same way one defines shell variables,
as in:
.if t \f(CWNAME=value\fP,
.if n NAME=value,
one per line.
There are three sorts of parameters,
strings, arrays of strings, and numbers.
String arrays are merely comma (`,') separated strings,
as in:
.if t \f(CWMAILERARGS="-A","-B"\fP.
.if n MAILERARGS="-A","-B".
Spaces or tabs around the `\fB=\fP' will be ignored,
as will trailing spaces and tabs.
Strings may be enclosed in double-quotes, which will be ignored.
Double-quotes may be escaped with a backslash (`\e').
Commas within quoted strings are ignored.
Numbers are hexadecimal if they have a leading `0x',
octal if they have a leading `0',
otherwise decimal.
.PP
Comments may be introduced with a hash character (`#')
at the start of a line,
and continue to the end of the line.
Empty lines are ignored.
.PP
The parameters
.SM NCC_MANAGER
and
.SM NCC_ADMIN
which contain network addresses may contain several addresses separated by spaces.
.br
.ne 10
.SS Defaults
The following parameters may be changed:
.PP
.nf
.ta +\w'\s-1\f(CWFILESEXPIREDAYS\fP\s0X'u +\w'\s-1\f(CW"-cB -D16 -R300 -S10 -X30"\fP\s0X'u
Name	Default	File
.ft CW
.ps -1
.vs \n(.s+2
.sp .25
ADDRESS	""	netmail
ACKMAIL	0	netmail
BINMAIL	/bin/mail	\*(MP
BINMAILARGS	""	\*(MP
DFLTPARAMS	"-cB -D16 -R300 -S10 -X30"	daemon
FILESERVERLOG	\*(sT_stats/servedfiles	fileserver
FILESERVER_MAXC	80	fileserver
FILESERVER_MAXL	0	fileserver
FILESERVER_NOLR	0	fileserver
FILESERVER_NOX	0	fileserver
FILESEXPIREDAYS	14	filer
FILTERPROG	\*(sT_lib/filter.sh	filtername
FOREIGNUSERNAME	daemon	spoolername
GETFILE	netget	filer
HANDLERPROG	\*(sT_lib/handler.sh	handlername
IGN_ETCPASSWD	0	daemon
IGNMAILERSTATUS	0	mailer
KEEPSTATE	1	stater
LOCALSEND	1	\*(MP
LOCAL_NODES	""	\*(MP
LOGFILE	\*(sT_stats/link.fltr.log	filtername
MAILER	/bin/mail	mailer
MAILERARGS	""	mailer
MAIL_FROM	1	mailer
MAIL_RFC822_HDR	1	\*(MP
MAIL_TO	1	\*(MP
MAX_MESG_DATA	2097152	\*(MP
MESSAGEID	0	netmail
MINSPOOLFSFREE	100	\*(MP
MKDIR	/bin/mkdir	\*(MP
NCC_ADMIN	root	\*(MP
NCC_MANAGER	root	\*(MP
NETADMIN	0	\*(MP
NETGROUPNAME	daemon	\*(MP
NETUSERNAME	daemon	\*(MP
NEWSARGS	""	reporter
NEWSCMDS	\*(sT_lib/newscmds	reporter
NEWSEDITOR	/usr/bin/rnews	reporter
NEWSIGNERR	0	reporter
NICEDAEMON	-5	daemon
NICEHANDLERS	10	\*(MP
NOADDRCOMPL	1	\*(MP
NODENAMEFILE	""	\*(MP
NORET	0	netmail
NVETIMECHANGE	10	netinit,daemon
NVETIMEDELAY	600	netinit
PORT	1989	tcplisten
POSTMASTER	root	\*(MP
POSTMASTERNAME	Postmaster	\*(MP
PRINTER	/usr/bin/lpr	printer
PRINTERARGS	"-C","&F:&O","-J","&D"	printer
PRINTORIGINS	_lib/printorigins	printer
PRIVSFILE	\*(sT_lib/privsfile	\*(MP
PUBLICFILES	\*(sT_lib/publicfiles	fileserver
RECEIVED	0	netmail
RECEIVER	\*(sT_lib/spooler.sh	spoolername
RMDIR	/bin/rmdir	\*(MP
SENDACKARGS	"-au -Amailer -NMail"	netmail
SENDARGS	"-u -Amailer -NMail"	netmail
SENDER	\*(sT_lib/sendfile	netmail
SERVER	\*(sT_lib/tcpshell	tcplisten
SERVERGROUP	fileserver	fileserver
SERVERUSER	fileserver	fileserver
SERVICE	mhsnet	tcplisten
SHELL	/bin/sh	\*(MP
SHOW_ROUTE	0	mailer
SPOOLDIR	/usr/spool/MHSnet	\*(MP
STATE	\*(sT_lib/netstate	\*(MP
STATERNOTLIST	_state/ignorefile	stater
STOP	netstop	\*(MP
STTY	/bin/stty	\*(MP
.if \n(S3 \{\
SUN3	0	\*(MP\}
.\".if \n(S3 \{\
.\"SUN3	0	\*(MP
.\"SUN3LIBDIR	_lib	sun3
.\"SUN3SPOOLDIR	/usr/spool/ACSnet	sun3
.\"SUN3STATEP	/usr/bin/acsstate	sun3
.\"SUN3USERNAME	daemon	sun3
.\"SUN3WORKDIR	_work	sun3\}
TMPDIR	/tmp	\*(MP
TRACEFLAG	0	\fI(any file)\fP
ULIMIT	2097152	\*(MP
UUCPLCKDIR	/usr/spool/uucp	daemon
UUCPLCKPRE	LCK..	daemon
UUCPLOCKS	1	daemon
UUCPLOWERDEV	0	daemon
UUCPMLOCKDEV	0	daemon
UUCPSTRPID	0	daemon
VALIDATEMAIL	0	mailer
VCDAEMON	\*(sT_lib/VCdaemon	daemon
WHOISARGS	"-i","-e"	peter
WHOISFILE	/usr/pub/whois	peter
WHOISPROG	/usr/bin/egrep	peter
.DT
.ft
.ps
.vs
.fi
.PP
Those fields tagged with an asterisk will have the value of
.SM SPOOLDIR
prepended if they don't start with a leading `/'.
.SS Note
You should not change the value of
.SM SPOOLDIR
while there are messages on any of the queues,
since the message descriptors contain absolute pathnames.
.PP
If you change
.SM NETUSERNAME
or
.SM NETGROUPNAME
then you must also change all the ownerships in \*(sD
from the old value to the new value.
.SS Definitions
.if n .ds tw 4
.if t .ds tw \w'\s-1FOREIGNUSERNAME\s0X'u
.TP "\*(tw"
.SM ADDRESS
Set this to override the default `site' address for
.I netmail (1).
.TP
.SM ACKMAIL
Set this to \fB1\fP if you wish to turn on automatic acknowledgment
for all mail generated by
.I netmail (1).
.TP
.SM BINMAIL
This defines the name of the program that will be used to deliver
mail generated internally by the network, eg: acknowledgments of
correctly delivered files, or error reports to the
.I NCC_MANAGER .
It must be able to read the body of the mail text from its standard input,
and to accept many user addresses as arguments
(after any special arguments mentioned in \s-1BINMAILARGS\s0 below).
.if t \f(CW/bin/mail\fP
.if n `/bin/mail'
should always work,
as the network will terminate if it can't deliver a management message.
.TP
.SM BINMAILARGS
If you have a version of mail that understands about interpolating the
origin host address in the mail item,
then this is where you tell it what to do.
For example, a particular mail program may
use the argument `\fB\-n\fP\fIuser\fP\fB@\fP\fIhost\fP'
to tell mail that we wish the item to appear to come
from someone other than the invoker;
ie: we set \s-1BINMAILARGS\s0 to be
.if t \f(CW"-n&F@&O"\fP.
.if n "-n&F@&O".
.TP
.SM DFLTPARAMS
The default parameters
to be used by the transport daemons
if the connection fails to negotiate properly.
.TP
.SM FILESERVERLOG
The name for an optional file which will be used to log fileserver requests.
.TP
.SM FILESERVER_MAXC
The maximum number of columns allowed when listing pathnames.
If a path name is longer than this,
it is truncated at the front with the truncated part replaced by elipses.
[No truncation if \fB0\fP.]
.TP
.SM FILESERVER_MAXL
The maximum size of a fileserver listing request that will be returned.
Long listings are truncated to this length.
[No truncation if \fB0\fP.]
(It is suggested that a pre-prepared recursive directory listing
be placed in a file named
.if t \f(CWls-lRt.Z\fP
.if n `ls-lRt.Z'
to make it unnecessary for requesters to do recursive verbose listings.)
.TP
.SM FILESERVER_NOLR
Setting this parameter to \fB1\fP disables recursive listing requests to the fileserver.
.TP
.SM FILESERVER_NOX
Setting this parameter to \fB1\fP disables `in-place' file transmission by the fileserver.
Instead copies will be made of each file requested.
This is useful if files are being serviced that change frequently,
as it prevents the use of the \fB\-X\fP flag to 
.IR netfile (1),
which can cause the transport daemons to complain if an `in-place' file
changes size between being requested and being transmitted.
.TP
.SM FILESEXPIREDAYS
After files have been spooled at a site for delivery to a local user,
the user is notified by mail that the files have arrived,
and warned that the spooled files will be deleted
after a certain number of days.
This is where you specify that period.
It is effected by a periodic command run by
.I netinit .
.TP
.SM FILTERPROG
Defines the name of the program to be run by a message
.I filter
to process the data from a message,
defaults to:
.if t \f(CWfiltername.sh\fP,
.if n `filtername.sh',
where
.I filtername
is the name the filter was invoked with.
.TP
.SM FOREIGNUSERNAME
Defines the user id that will own files
passed to the foreign network interface,
defaults to: \s-1NETUSERNAME\s0.
.TP
.SM GETFILE
The name of the program used by a user to get files they have been sent.
.TP
.SM HANDLERPROG
Defines the name of the program to be run by a message
.I handler
to process the data from a message,
defaults to:
.if t \f(CWhandlername.sh\fP
.if n `handlername.sh',
where
.I handlername
is the name the handler was invoked with.
.TP
.SM IGN_ETCPASSWD
Setting this to \fB1\fP causes
.I netshell (8)
to ignore any entry in the
.if t \f(CW/etc/passwd\fP
.if n `/etc/passwd'
file and force a check of the network region password
for a matching site (if set).
.TP
.SM IGNMAILERSTATUS
This parameter refers to the exit status of the program defined in
.SM MAILER
below.
Some delivery programs, notably
.if t \f(CWsendmail\fP
.if n `sendmail'
from 4\s-1BSD\s0,
return non-zero exit status,
even when they have done something sensible with the mail item.
In this case, the handler would normally assume that something went wrong,
and return the mail item to its origin with an appropriate error message,
but you can suppress this action by defining this flag to be \fB1\fP.
If the mailer returns the exit status 67 [\s-1EX_NOUSER\s0]
as well as sending a separate reply for non-existent user errors,
then set this flag to \fB2\fP,
and only that error status will be ignored.
.TP
.SM KEEPSTATE
This parameter controls the building of the site information data-base
used for quick reference by
.I netmap (1)
when showing the details for a particular site.
It causes the last state message received from each site to be saved
in a directory tree starting at
.if t \*(sD\f(CW/_state/MSGS\fP.
.if n `\*(sD/_state/MSGS'.
Set it to \fB0\fP to prevent saving.
.TP
.SM LOCALSEND
Set this to 1 if you wish to allow users
whose network \s-1SEND\s0 permission
has been denied in the `netprivs' file (see
.I netprivs (5))
to be able to
use the network to send messages to other users on the same node.
.TP
.SM LOCAL_NODES
This is a more extensive version of \s-1LOCALSEND\s0,
in that you can nominate a set of nodes to which messages
may be sent by users otherwise denied
network \s-1SEND\s0 permission.
It can either be a list of network addresses,
or the name of a file containing the list.
The addresses can be separated by <tab> or <newline>.
.TP
.SM LOGFILE
If a message filtering program defined in
\s-1FILTERPROG\s0 doesn't exist,
or is unexecutable,
then
.I netfilter (8)
defaults to logging information about the message
in the file defined by this parameter.
If this parameter is undefined,
it defaults to
.if t \f(CW_stats/\fP\fIlink\fP\f(CW.fltr.log\fP
.if n `_stats/\fP\fIlink\fP\f(CW.fltr.log'
where
.I link
is the name of the link the filter is invoked for.
.TP
.SM MAILER
This defines a program that will be used to deliver mail
received off the network, ie: from users at other hosts.
It must behave in the same way as \s-1BINMAIL\s0 above,
and again,
.if t \f(CW/bin/mail\fP
.if n `/bin/mail'
should always work.
However, if you have a special program used just for
.I delivering
mail, then this is the place to specify it.
.TP
.SM MAILERARGS
If \s-1MAILER\s0 can be told where the mail originated,
then it should be specified in this argument,
much the same as for \s-1BINMAILARGS\s0 above.
Please note that this is the only safe way to guarantee that
mail `From' lines are valid.
\s-1MAILER\s0 should interpolate this string in place of
any user/site addresses in the body of the mail item.
.TP
.SM MAIL_FROM
If your version of \s-1MAILER\s0 does not correct the `From' line
using the information from \s-1MAILERARGS\s0,
then setting this to \fB1\fP
will enable the mail handler itself
to add a standard \s-1UNIX\s0 mail header.
.TP
.SM MAIL_RFC822_HDR
Setting this to \fB1\fP causes internally generated mail
to include an \s-1RFC\s0822 compliant mail header.
.TP
.SM MAIL_TO
Setting this to \fB1\fP causes internally generated mail to include a
`To:\ ' header line.
.TP
.SM MAX_MESG_DATA
This is the maximum message size that is sent through the network.
Messages larger than this are broken into \s-1MAX_MESG_DATA\s0 sized parts and
sent independently through the network and reassembled before delivery.
.TP
.SM MESSAGEID
Set this to \fB1\fP to cause
.I netmail (1)
to generate an RFC822 compliant
.if t \f(CWMessage-ID: \fP
.if n `Message-ID: '
line in every header.
.TP
.SM MINSPOOLFSFREE
This is the minimum amount of free space desired
on the network spool file-system (in kilobytes).
When the free space falls below this,
the message creating programs will either wait for more space to become available
(eg: the transport daemon receiver process \(em see
.I netdaemon (8)),
or return error codes (eg:
.I netfile (1)).
.TP
.SM MKDIR
The command for making a directory.
.TP
.SM NCC_ADMIN
This defines the name of the person
to whom network generated error reports are sent.
By preference a local network wizard,
maybe
`Postmaster',
or possibly
`root',
alternatively it may be the network address of
someone central who fixes problems
in your branch of the network.
This is most useful when you have a large network
with central control.
.TP
.SM NCC_MANAGER
In contrast to
\s-1NCC_ADMIN\s0,
this defines the name of the person
to whom network generated information reports are sent.
Usually the same as
\s-1NCC_ADMIN\s0,
alternatively it may be the network address of
someone central who collects information on your branch of the network.
.TP
.SM NETADMIN
Set to \fB1\fP to cause mail notices of new regions added to routing tables
to be sent to \s-1NCC_MANAGER\s0.
Also causes notification of new/deceased links to your site,
and turns on state broadcast logging in
.if t \*(sD\f(CW/_state/log\fP.
.if n `\*(sD/_state/log'.
Set it to \fB2\fP if you want
mail notices every time a new site sends its first state message,
or a calling site has problems.
Set it to \fB3\fP if you want
mail notices every time a link changes state (up/down).
.TP
.SM NETGROUPNAME
The group id used by network processes.
.TP
.SM NETUSERNAME
The user id used by network processes.
.TP
.SM NEWSARGS
Any arguments for \s-1NEWSEDITOR\s0.
.TP
.SM NEWSCMDS
This should be the name of a file which is used by the news message handler
.I reporter
to provide the full pathname of a news command and any extra arguments.
This can safely be ignored until you become a sophisticated news gatherer.
The file should contain lines of the form:
.in +2
.ps -2
.nf
.if t .ft CW
command<tab>full_path_name[<space>arg ...]
.if t .ft
.fi
.ps
.in
You should consult with your news neighbours to determine
the necessary commands to install here (if any).
.TP
.SM NEWSEDITOR
If you participate in the
.I netnews
system,
this argument specifies the news receiver program
to be invoked by the news message handler
.I reporter .
.TP
.SM NEWSIGNERR
Some versions of
.I rnews
return non-zero exit status when they receive a null news item.
If these are a frequent occurrence,
or you simply wish to ignore all delivery errors for news items,
then you can suppress the error reports by defining this flag to be \fB1\fP.
It is probably a good idea to leave the value at \fB0\fP (the default)
until you are sure that normal
news items are being delivered correctly.
.TP
.SM NICEDAEMON
If you wish the transport daemons to run at a non-standard priority,
then this parameter should be defined as for use in the
.IR nice (2)
system call.
For instance, if you wanted the network to run only when there was
idle \s-1CPU\s0 time, then give it the value 19.
However, be aware that if you do this when the system is busy,
then the links may appear to go up and down a lot.
Using a value of \-5 will ensure the transport daemons
always achieve high throughput,
which is acceptable since they are not very \s-1CPU\s0 intensive.
A value of 0 is probably safe.
.TP
.SM NICEHANDLERS
When a message arrives,
and is passed to the routing program to be processed,
this parameter will cause the handlers to be run at a different priority
from the daemon.
We use a value of 10, which is nice to users.
This parameter may also be specified on a per-handler basis by altering the
appropriate field in the
.I handlers
file (see
.IR nethandlers (5).)
Note that the router processes messages serially,
so slowing down a particular handler will also delay any following messages
(but see
.IR nethandlers (5)
for a way to specify asynchronous \fIsub\fP-routers for particular handlers).
.TP
.SM NOADDRCOMPL
Set to \fB0\fP to allow address completion.
Without address completion,
every network address must have all domains present,
up to and including the \s-1COUNTRY\s0-level domain,
or be fully typed.
If address completion is allowed,
then addresses ending in any untyped domain
that matches one in the local hierachy
will have the remainder of the hierarchy appended.
This may not be a good idea if any domain in the hierarchy
happens to be the same as a valid \s-1COUNTRY\s0 code,
or other domain in the routing tables.
.TP
.SM NODENAMEFILE
If your \s-1UNIX\s0 kernel is a variant
of neither \s-1SYSTEM V\s0, nor \s-1BSD\s04.x, then
this parameter names a file where the name of your node is kept.
This name is used in displaying which nodes in a distributed file system the
various network daemons are running on.
This is needed since the network
name of the collection of nodes in all probability will be different.
.TP
.SM NORET
Setting this to \fB1\fP will cause
.I netmail
to request that all delivery errors be ignored for mail messages it generates.
.TP
.SM NVETIMECHANGE
The maximum negative system time change (in seconds)
tolerated by time sensitive daemons [default: 10 seconds].
.TP
.SM NVETIMEDELAY
The time in seconds that
.I netinit (8)
will delay after detecting a negative system time change
greater than
.SM NVETIMECHANGE
before re-starting network processes [default: 600 \(em 10 minutes].
.TP
.SM PORT
The port number used by \*(sN \s-1TCP/IP\s0 connections.
.TP
.SM POSTMASTER
This must be set to be a name that messages returned from your node
may legally be sent to in the case of the origin also returning them.
If your mail program doesn't recognise anything special such as
\s-1POSTMASTER\s0, then this must be the name of a real user [default: root].
International networking conventions require that
`postmaster'
be a valid mail address on your system as a way to
guarantee deliveries of enquiries and mail problem reports,
so the mail message handler intercepts any case of `postmaster'
and interpolates the value of this parameter.
.TP
.SM POSTMASTERNAME
Set to a string to be used in mail `From' lines in mail internally generated by \*(sN
[default: Postmaster].
.TP
.SM PRINTER
The name of the program used to spool print jobs from the network.
Leave it undefined if this host has no printer,
or if you have no intention of letting other sites print their jobs here.
(But see \s-1PRINTORIGINS\s0 below.)
.TP
.SM PRINTERARGS
Any arguments for \s-1PRINTER\s0.
.TP
.SM PRINTORIGINS
If you \fBdo\fP define \s-1PRINTER\s0, then you will need to restrict
the sites from which you are prepared to accept print jobs.
This parameter can be either the path name of a file
containing a list of legal network origins for print jobs,
or just a list of sites specified as a multicast address.
.TP
.SM PRIVSFILE
The name of a file where network users' privileges will be listed
(see
.IR netprivs (5)).
.TP
.SM PUBLICFILES
Defines the directory (or name of a file containing directories)
where publicly accessible files are held.
.TP
.SM RECEIVED
Setting this to \fB1\fP will cause
.I netmail
to generate an RFC822 compliant
.if t `\f(CWReceived:\ \fP'
.if n `Received:\ '
line in every mail header.
.TP
.SM RECEIVER
Defines the name of the program to be run by a message
.I spooler
to process the data from a message,
defaults to:
.if t \f(CWspoolername.sh\fP,
.if n `spoolername.sh',
where
.I spoolername
is the name the spooler was invoked with.
.TP
.SM RMDIR
The command for removing a directory.
.TP
.SM SENDACKARGS
Defines the args to be passed to \s-1SENDER\s0
to send a mail message with an acknowledgment request.
.TP
.SM SENDARGS
Defines the args to be passed to \s-1SENDER\s0 to send a mail message.
.TP
.SM SENDER
Defines the name of the program to send a network mail message.
.TP
.SM SERVER
The name of the program used to receive \*(sN \s-1TCP/IP\s0 connections.
.TP
.SM SERVERGROUP
The group name to run the file service under.
.TP
.SM SERVERUSER
The user name to run the file service under.
.TP
.SM SERVICE
The name of the `service' used when establishing a \*(sN \s-1TCP/IP\s0 connection.
.TP
.SM SHELL
The name of the command interpreter to be used by network `shell' scripts.
.TP
.SM SHOW_ROUTE
Set this flag to \fB1\fP to show the message route by adding
.IR Received :
lines to mail headers.
.TP
.SM SPOOLDIR
This should be the name of a directory
where all the network activity will take place.
It will contain all the messages that are
.I "in flight"
as well as the handler programs and network state files.
It should be somewhere safe,
where the integrity of the messages is least likely to be compromised,
(so try and avoid less than fully reliable disk drives.)
The usual choice would be:
.if t \f(CW/usr/spool/MHSnet\fP.
.if n `/usr/spool/MHSnet'.
.br
\fBNOTE:\fP if you change \*(sD then any other parameters containing
\*(sD must also be changed.
.TP
.SM STATE
The pathname of the `netstate' command.
.TP
.SM STATERNOTLIST
This parameter allows you to nominate a set of nodes whose state
messages will be ignored if they arrive more frequently than once an hour.
It can either be a list of network addresses,
or the name of a file containing the list. eg:
.br
.if t .ft CW
\s-1STATERNOTLIST=*.su.oz.au\s0
.if t .ft
.br
The addresses in `ignorelist' can be separated by <tab> or <newline>.
.TP
.SM STOP
The pathname of the `netstop' command.
.TP
.SM STTY
The pathname of the `stty' command.
.TP
.SM SUN3
Set this to 1 if you wish the `.au' to be stripped
from the end of mail addresses ending in `.oz.au'
(for backward compatibility with sites running the \*(sM software).
.TP
.SM TMPDIR
The pathname of the directory to use for temporary files.
.TP
.SM TRACEFLAG
Turns on program tracing at a level between \fB1\fP and \fB9\fP.
.TP
.SM ULIMIT
The size of the `ulimit' value used by network processes.
.TP
.SM UUCPLCKDIR
The name of the directory where `uucp' creates its lock files.
.TP
.SM UUCPLCKPRE
The prefix for `uucp' lock file names,
normally
.if t \f(CWLCK..\fP
.if n `LCK..',
which is followed by the device name.
.TP
.SM UUCPLOCKS
Set this to \fB1\fP to turn on `uucp' locking for device access.
.TP
.SM UUCPLOWERDEV
Set this to \fB1\fP if `uucp' lock files
must have the last char of the `tty' name forced to lower-case,
common in SCO versions where `tty' names have an upper-case char
to indicate dial-out copy of a modem line,
(default: copy of `tty' name in `/dev').
.TP
.SM UUCPMLOCKDEV
Set this to \fB1\fP if `uucp' lock files
are named after the major/minor device numbers,
rather than the `tty' name in `/dev',
(default: copy of `tty' name in `/dev').
.TP
.SM UUCPSTRPID
Set this to \fB1\fP if `uucp' lock files
contain the locking process \s-1ID\s0 in \s-1ASCII\s0,
(default: binary integer).
.TP
.SM VALIDATEMAIL
Some mail delivery programs are guaranteed to
fail
(dump a
.I core
file, or write a
.I dead.letter
file)
if the destination user doesn't exist, in which case the handler
might as well check first that the user exists in the password file.
You can force this check to happen by defining this flag to be \fB1\fP.
.TP
.SM VCDAEMON
The name of the default virtual circuit daemon.
.TP
.SM WHOISARGS
Any additional arguments you might want to pass to \s-1WHOISPROG\s0.
.TP
.SM WHOISFILE
The name of the people data-base.
It should contain all the information about your users
that is deemed publicly accessible.
A carefully pruned copy of
.if t \f(CW/etc/passwd\fP
.if n `/etc/passwd'
would do, but you should convert all capitals to lower-case,
unless your version of
\s-1WHOISPROG\s0 has an `ignore case' flag,
(in which case turn it on in \s-1WHOISARGS\s0 above).
For example,
you could use the following command
(perhaps run once a month by
.I cron\c
) to make the pruned
.I whois
file:
.in +2
.nf
.ft CW
cut -d: -f1,5 /etc/passwd |
tr '[A-Z]' '[a-z]' >/usr/pub/whois
.ft
.fi
.in
.TP
.SM WHOISPROG
The name of the program which will attempt to match the supplied pattern
in the
.I whois
data-base.
It will be passed arguments as for
.IR egrep (1),
which is the obvious candidate.
.br
.ne 10
.SH EXAMPLE
The file \*(NP might contain:
.PP
.RS 2
.ft CW
.nf
BINMAIL=/usr/lib/delivermail
BINMAILARGS="%B-b%","%+L-l%","&L","&F@&O"
NCC_MANAGER="postmaster fred@mhs.oz.au"
NETADMIN=2
SPOOLDIR=/var/local/spool/net
.DT
.fi
.ft
.RE
.br
.ne 3
.SH "SEE ALSO"
.IR \*(S5 (7),
.IR netparams (8).
.br
