.nr S3 1 \" 1 for ACSnet
.ds S1 NETSHELL
.ds S2 \fINetshell\fP
.ds S3 \fInetshell\fP
.ds S4 MHSnet
.ds S5 network
.ds S6 _lib/*shell
.ds SR \fI\s-1SDIR\s0\fP
.TH \*(S1 8 "\*(S4 1.23" \^
.nh
.SH NAME
netshell \- login shells for intermittent network connections
.SH SYNOPSIS
.BI \*(S6
.SH DESCRIPTION
\*(S2
can be specified to be the login shell for accounts representing remote hosts
that will make intermittent connections to exchange queued network messages.
The alternate names are for the various types of virtual circuit that can be accepted.
On invocation,
\*(S3
will accept the connection if necessary,
search the routing tables for the real name of the link,
move to the link's operating directory (creating it if necessary),
condition the virtual circuit for use by the message transport protocol,
and then negotiate the parameters for the daemon.
.PP
For connections via the standard login process,
a suitable version of \*(S3 should be entered as the
.I shell
for the login account.
The account name should be either the nodename for the site, or an
.I alias
for the real network name of the connecting site
(see the
.I map
command in
.IR netstate (8)).
For example,
a dial-in link from a site
`altair.com.mhs.au'
might have the following account set up
(where \*(SR represents the pathname of the network operating directory,
normally
.if t \f(CW/usr/spool/MHSnet\fP):
.if n `/usr/spool/MHSnet'):
.PP
.RS 1
.nf
.ft CW
.if \n(.lu<6i .ps -2
altair::18:1:\*(S4 login:\*(SR:_lib/ttyshell
.if \n(.lu<6i .ps
.ft
.fi
.RE
.PP
You ought either to set a password for the account,
or use
.IR netpasswd (8)
to set a password for the network name,
(particularly to protect \s-1IP\s0 type connections).
.PP
For \s-1IP\s0 type connections,
suitable entries should be made in the
.if t \f(CW/etc/servers\fP
.if n `/etc/servers'
file,
eg:
.PP
.RS
.nf
.ft CW
mhsnet udp \*(SR/_lib/udpshell
mhsnet tcp \*(SR/_lib/tcpshell
.ft
.fi
.RE
.PP
or in the
.if t \f(CW/etc/inetd.conf\fP
.if n `/etc/inetd.conf'
file,
eg:
.PP
.RS
.nf
.ft CW
.if \n(.lu<6i .ps -2
mhsnet dgram udp wait root \*(SR/_lib/udpshell udpshell
mhsnet stream tcp nowait root \*(SR/_lib/tcpshell tcpshell
.if \n(.lu<6i .ps
.ft
.fi
.RE
.PP
.if \n(S3 \{\
If you have an \s-1IP\s0 connection to a 
.SM "SUN\ III"
site, then you also need:
.PP
.RS
.nf
.ft CW
.if \n(.lu<6i .ps -2
acsnet dgram udp wait root \*(SR/_lib/ENshell ENshell
acsnet stream tcp nowait root \*(SR/_lib/TNshell TNshell
.if \n(.lu<6i .ps
.ft
.fi
.RE\}
.PP
If your system lacks a version of 
.if t \f(CW/etc/inetd.conf\fP
.if n `/etc/inetd.conf'
(on some systems called
.if t \f(CW/etc/servers\fP),
.if n `/etc/servers'),
you may have to make use of the program
.IR netlisten (8).
.SH "SHELLPROG"
If a file named
.if t \f(CWshellprog\fP
.if n `shellprog'
exists in the link's operating directory,
or if not there, then in the
.if t \f(CW_call\fP
.if n `_call'
directory,
it will be executed in the transport daemon's operating directory by
.IR sh (1)
before the message transport daemon is started.
It will be passed three arguments:
the name of the link,
the name of the transport daemon,
and the invoked name of \*(S3.
It will have standard input and output set to the virtual circuit,
and should return a zero exit status.
A non-zero exit status will cause \*(S3 to exit without starting a daemon.
Note that if
.if t \f(CWshellprog\fP
.if n `shellprog'
has an owner other than
.SM NETUSERNAME
or a group other than
.SM NETGROUPNAME,
or is publicly writeable,
then it will be ignored.
.SH "ANONYMOUS CONNECTIONS"
You may allow connections from sites which don't have a pre-arranged link
to your site by validating them in the network `password' file
(see
.IR netpasswd (8)).
This file can contain any network addresses you wish to allow connections from.
In particular, if any address is in the form of a broadcast address,
then it validates connections from any node within the broadcast region.
.PP
You should then create and publish your site's `anonymous' login account
(or IP address), eg:
.PP
.RS 1
.nf
.ft CW
.if \n(.lu<6i .ps -2
mhsnet::18:1:Anonymous \*(S4 logins:\*(SR:_lib/ttyshell
.if \n(.lu<6i .ps
.ft
.fi
.RE
.PP
The account name should be something that can't be recognised as a site address,
because if \*(S3 can't find a link to match the login name (or IP source address),
then it will ask for one by sending the line:
.RS
.ft CW
QUERY HOMENAME
.ft
.RE
.PP
It will then wait up to 20 seconds for a reply in the form:
.RS
.ft CW
HOMENAME <address>[ {CRC}]
.ft
.RE
.PP
The
.I address
should be the one provided to the caller's
.I call-script
in the variable
.SM HOMENAME
(See
.IR netcall (8).)
.PP
The optional trailer for the \s-1HOMENAME\s0 line
is a 16-bit \s-1CRC\s0 generated by the
.B crc
command in a
.IR call-script .
If it doesn't match, then the \s-1HOMENAME\s0 line will be ignored,
and the query repeated, up to 10 times.
.PP
If the `password' file exists,
and if the given
.I address
matches an entry in the file,
then \*(S3 will allow a
new link from
.I address
to the local node to be created.
If the address matched was a
.I broadcast
address,
then this link will be marked
.if n `dead,nochange'
.if t \f(CWdead,nochange\fP
in the outbound direction so that any pre-existing connection to
.I address
will still be the preferred route.
Should you wish this new link to carry out-bound traffic in preference to other routes,
then you should arrange to mark the link up
and remove the
.if n `nochange'
.if t \f(CWnochange\fP
flag
.if n (`\-dead,-nochange')
.if t (\f(CW-dead,-nochange\fP)
\(em see
.IR netstate (8).
.PP
If the calling site isn't validated,
\*(S3 will terminate the connection after sending the line:
.RS
.ft CW
CONNECTION DISALLOWED
.ft
.RE
.PP
Sensitive links should always be protected with a network password.
.SH "CALL PARAMETER NEGOTIATION"
If the network control program
.RI ( netinit (8))
is inactive,
\*(S3 will terminate the connection after sending the line:
.RS
.ft CW
NETWORK INACTIVE
.ft
.RE
.PP
If a network password has been set for the calling site,
or if a network password has been set for a region containing the calling site
and there is no
.if t \f(CW/etc/passwd\fP
.if n `/etc/passwd'
entry for the caller, or the
.SM IGN_ETCPASSWD
parameter is set,
\*(S3 will send the line:
.RS
.ft CW
QUERY PASSWORD
.ft
.RE
.PP
It will then wait up to 20 seconds for a reply in the form:
.RS
.ft CW
PASSWORD <password>[ {CRC}]
.ft
.RE
.PP
The optional 
.SM CRC
is processed as for
.SM HOMENAME
above.
If the password doesn't match,
then \*(S3 will terminate with the error:
.RS
.ft CW
FAILED PASSWORD
.ft
.RE
.PP
If a daemon is already active for the link,
\*(S3 will terminate the connection after sending the line:
.RS
.ft CW
DAEMON ALREADY ACTIVE
.ft
.RE
.PP
\*(S2 will then send the line
.RS
.ft CW
SHELL STARTS 2V
.ft
.RE
[`ttyxshell' sends]
.RS
.ft CW
XON_XOFF SHELL STARTS 2V
.ft
.RE
and wait up to 20 seconds for either the reply:
.RS
.ft CW
VCCONF <param> ... [ {CRC}]
.ft
.RE
(to which it will reply)
.RS
.ft CW
QUERY DAEMON
.ft
.RE
and/or the reply:
.RS
.ft CW
DAEMON <daemon name> [ {CRC}]
.ft
.RE
(to which it will reply)
.RS
.ft CW
QUERY PARAMS
.ft
.RE
and/or the reply:
.RS
.ft CW
PARAMS <daemon arg> ... [ {CRC}]
.ft
.RE
to which it will reply:
.RS
.ft CW
DAEMON STARTS DAEMON STARTS
.ft
.RE
(repeated to ensure a match).
.PP
The daemon will then be started with the passed parameters.
.PP
Note that earlier versions just send:
.RS
.ft CW
SHELL STARTS
.ft
.RE
and don't expect the
.SM DAEMON
or
.SM VCCONF
responses, so call scripts should differentiate.
(Some intermediate versions send
.RS
.ft CW
SHELL STARTS 2
.ft
.RE
and don't expect the
.SM VCCONF
response.)
The default daemon is `VCdaemon' (see
.IR netdaemon (8)).
.PP
The optional 
.SM CRC
is processed as for
.SM HOMENAME
above.
.PP
If the negotiation times out,
it will send the line:
.RS
.ft CW
DEFAULT STARTS
.ft
.RE
and a daemon will be started with the following
.I worst-case
parameters:
.RS
.ft CW
-c -B -D16 -R300 -S10 -X30
.ft
.RE
Ie:
cooked mode,
batch mode,
16 byte packets,
maximum run time of 5 minutes,
minimum speed of 10 bytes/second,
and expected throughput of 30 bytes/second.
(See
.I netdaemon (8).)
These parameters may be changed via the value for
.SM DFLTPARAMS
in the alternate parameters file, see below.
.PP
These parameters may be overridden if necessary by the contents of a file named
.if t \f(CWparams\fP
.if n `params'
in the link's operating directory, or,
if specific to a particular version of \*(S3,
by files named as follows:
.PP
.RS 2
.nf
.ta +\w'ttyxshellXX'u +\w'ttyxparamsXX'u
\fBShell	File name	Connection type\fP
.sp .5
tcpshell	tcpparams	\s-1TCP/IP\s0 connection
ttyshell	ttyparams	`tty' connection
ttyxshell	ttyxparams	`tty' with \s-1XON/XOFF\s0
udpshell	udpparams	\s-1UDP/IP\s0 connection
x25shell	x25params	X.25 connection
.if \n(S3 \{\
.sp .5
NNshell	NNparams	\s-1SUN III\s0 `tty' connection
XNshell	XNparams	\s-1SUN III\s0 `tty' with \s-1XON/XOFF\s0
CNshell	CNparams	\s-1SUN III\s0 `tty' with high error rate
PNshell	PNparams	\s-1SUN III\s0 `tty' with large packets
TNshell	TNparams	\s-1SUN III TCP/IP\s0 connection
ENshell	ENparams	\s-1SUN III UDP/IP\s0 connection\}
.DT
.fi
.RE
.SH PARAMETERS
On starting,
\*(S3 reads the parameter file
.if t \f(CW_params/daemon\fP.
.if n `_params/daemon'.
This file can contain the following optional parameters:
.TP 4
.SM DFLTPARAMS
Default parameters for the transport daemon.
.TP
.SM IGN_ETCPASSWD
If set to \fB1\fP,
forces network passwords set by
.IR netpasswd (8)
to be checked even though there is also a password for the connecting site in the
.if t \f(CW/etc/passwd\fP
.if n `/etc/passwd'
file.
.TP
.SM NICEDAEMON
The
.IR nice (2)
value for the transport daemon.
.TP
.SM TRACEFLAG
Sets tracing level, equivalent to \fB\-T\fP flag.
.TP
.SM VCDAEMON
The name of the transport daemon.
If the value doesn't begin with a leading
.if t `\f(CW/\fP',
.if n `/',
then
.if t \*(SR\f(CW/_lib/\fP
.if n `\*(SR/_lib/'
will be prepended.
.SH FILES
.PD 0
.TP "\w'_call/\fIshellname\fP.logXX'u"
\fIlinkdir\fP/log
Opened by \*(S3 for error messages after
.I linkdir
has been found.
.TP
\fIlinkdir\fP/shellprog
Optional shell program.
.TP
\fIlinkdir\fP/*params
Optional parameters for message transport daemon selected by name of virtual circuit.
.TP
\fIlinkdir\fP/cmds/lock
Lockfile established to prevent simultaneous calls for this link.
.TP
_call/\fIshellname\fP.log
Log file created on startup with the invoked program name.
This log file records the time of the call,
and any errors that occur before the link's logfile is created.
.TP
_call/shellprog
Optional default shell program.
.TP
_lib/lock
Lockfile for network control program.
.TP
_lib/VCdaemon
Default
.I virtual-circuit
message transport daemon.
.TP
_params/daemon
Alternate parameters for the shell.
.TP
_state/routefile
Routing tables for resolving link aliases.
.PD
.SH "SEE ALSO"
.IR sh (1),
.IR netparams (5),
.IR network (7),
.IR netcall (8),
.IR netdaemon (8),
.IR netinit (8),
.IR netlisten (8),
.IR netpasswd (8),
.IR netstate (8).
.br
.ne 11
.SH "DIAGNOSTICS"
'\".ifn .ds tw 4
'\".ift \{\
'\".ie \n(.lu<6i .ds tw 4
'\".el .ds tw \w'\f(CWRegion\ `xxx'\ unreachable\fPX'u\}
.ds tw 4
.TP "\*(tw"
\f(CWCould not gethostbyaddr "peername"\fP
This error is produced by
.IR tcpshell .
The value returned by the
.IR getpeername (2)
system call failed to deliver a
.I "struct hostent"
descriptor when passed to
.IR gethostbyaddr (3).
This may mean that the local name server is incorrectly configured.
